# Generated by Django 2.2.2 on 2019-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
