# Generated by Django 2.2.2 on 2019-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('tax_number', models.CharField(blank=True, max_length=30)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=15)),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar'), ('CHF', 'Swiss Franc'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro'), ('MKD', 'Denar')], default='MKD', max_length=20)),
                ('subscription_package', models.CharField(choices=[('Бесплатен', 'Бесплатен'), ('Класик', 'Класик'), ('Премиум', 'Премиум')], default='Бесплатен', max_length=20)),
            ],
        ),
    ]
