# Generated by Django 2.2.2 on 2019-12-22 14:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=15)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('payment_due', models.DateField()),
                ('place', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('invoice_sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('full_sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paid_sum', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
