# Generated by Django 2.2.2 on 2019-12-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_sum',
        ),
    ]
