# Generated by Django 2.2.2 on 2019-12-22 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20191222_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_sum',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
