# Generated by Django 2.2.2 on 2019-12-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20191222_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('CHF', 'Swiss Franc'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro'), ('MKD', 'Denar')], default='MKD', max_length=20),
        ),
    ]
