# Generated by Django 2.2.2 on 2019-12-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20191222_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_sum',
            field=models.ManyToManyField(blank=True, to='payments.Payment'),
        ),
    ]
