# Generated by Django 2.2.2 on 2019-12-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20191222_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
