# Generated by Django 2.2.2 on 2019-12-29 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
