# Generated by Django 2.2.2 on 2020-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20200111_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
