# Generated by Django 2.2.2 on 2020-01-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20200111_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='id_number',
        ),
    ]
